# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=250)),
                ('teamNr', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=250)),
            ],
        ),
    ]
