# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bellbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=250)),
                ('SH', models.CharField(max_length=10)),
                ('IM', models.CharField(max_length=10)),
                ('CF', models.CharField(max_length=10)),
                ('CO', models.CharField(max_length=10)),
                ('RI', models.CharField(max_length=10)),
                ('PL', models.CharField(max_length=10)),
                ('ME', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='participatoryentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=250)),
                ('teamID', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='teamattributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('diversity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='teambellbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('bellbinmatrix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='teamHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('hoursmatrix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='teamMBTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('mbtimatrix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='teamQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('qualitymatrix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='teamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=250)),
                ('rankmatrix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=25)),
                ('initials', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('cellphone', models.CharField(max_length=25)),
                ('emailaddress', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='team',
            name='rond',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='size',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='team',
            name='teamID',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
    ]
